### ISSUE TITLE
鹹魚啓示錄

### ISSUE THREAD

**Issue by axionl** [axionl/axionl.github.io#1]
https://axionl.github.io/about/

**Comment by axionl** [comment]
第一個用於測試的評論

**Comment by rvier** [comment]
Hi,ArielAxionL

**Comment by wizardforcel** [comment]
该叫你小哥哥还是小姐姐呢。。。

**Comment by axionl** [comment]
> 该叫你小哥哥还是小姐姐呢。。。

小老弟（xD,（现在已经不用这个 github issue 当评论了，改成 disqus 了

**Comment by wizardforcel** [comment]
@axionl 

知道啦 XD
